# Generated by Django 2.2.4 on 2019-10-13 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('-', '---'), ('F', 'Female'), ('M', 'Male')], default='-', max_length=1)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_number', models.CharField(max_length=12)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('semester', models.CharField(choices=[('-', '---'), ('F', 'Female'), ('M', 'Male')], default='--', max_length=6)),
                ('year', partial_date.fields.PartialDateField()),
            ],
            options={
                'db_table': 'course',
                'unique_together': {('course_name', 'semester', 'year')},
            },
        ),
    ]
