# Generated by Django 2.2.4 on 2019-11-29 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_project_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_role', models.CharField(choices=[('student', 'student'), ('teaching-assistant', 'teaching-assistant')], default='student', max_length=20)),
                ('student_status', models.CharField(choices=[('pending-approval', 'pending-approval'), ('approved', 'approved'), ('decined', 'declined')], default='pending-approval', max_length=20)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offering', to='team_project_tracking.CourseOffering')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_student',
                'unique_together': {('course_offering', 'student', 'student_role')},
            },
        ),
        migrations.DeleteModel(
            name='CourseTeachingAssistant',
        ),
    ]
