# Generated by Django 2.2.4 on 2019-11-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_course', to='team_project_tracking.Course'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_status',
            field=models.CharField(choices=[('pending-approval', 'pending-approval'), ('active', 'active'), ('inactive', 'inactive')], default='pending', max_length=10),
        ),
    ]
