# Generated by Django 2.2.4 on 2019-10-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('--', '--'), ('fall', 'fall'), ('spring', 'spring'), ('summer', 'summer')], default='--', max_length=6),
        ),
    ]
