# Generated by Django 2.2.4 on 2019-11-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_tracking', '0002_auto_20191013_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
