# Generated by Django 2.2.4 on 2019-11-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_tracking', '0002_auto_20191119_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_status',
            field=models.CharField(choices=[('pending-approval', 'pending-approval'), ('active', 'active'), ('inactive', 'inactive')], default='pending', max_length=18),
        ),
    ]
