# Generated by Django 2.2.4 on 2019-11-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_tracking', '0002_auto_20191129_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
