# Generated by Django 2.2.4 on 2019-11-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_tracking', '0003_remove_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
