# Generated by Django 2.2.4 on 2019-11-21 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_tracking', '0005_auto_20191121_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
