# Generated by Django 2.2.4 on 2019-11-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_tracking', '0006_team_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('inactive', 'inactive')], default='pending', max_length=10),
        ),
    ]
