# Generated by Django 3.1.4 on 2021-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_tracking', '0006_projectupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='course_status',
            field=models.CharField(choices=[('active', 'active'), ('discontinued', 'discontinued')], default='active', max_length=15),
        ),
    ]
