# Generated by Django 2.2.4 on 2019-11-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_project_tracking', '0007_auto_20191121_0128'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['course', 'semester', 'year', 'faculty'], name='course_offe_course__c434f5_idx'),
        ),
    ]
