# Generated by Django 2.2.4 on 2019-11-27 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_project_tracking', '0009_auto_20191121_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='course_offering',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_course_role', to='team_project_tracking.CourseOffering'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('role', 'user', 'course_offering')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'user', 'course_offering'], name='user_role_role_id_b405e8_idx'),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='course',
        ),
    ]
